version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-mpc-password-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uzou80dlns8n"
s3_prefix = "sam-mpc-password-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
